services:
  backend:
    image: xgcdkr/trivia99-backend:latest
    #build: backend/    
    ports:
      - "4000:4000"
  frontend:
    image: xgcdkr/trivia99-frontend:latest
    #build: frontend/
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:3000"



