services:
  backend:
    build: backend/ 
    ports:
      - "4000:4000"

  frontend:
      build: frontend/ 
      depends_on:
        backend:
          condition: service_started
      ports: 
        - "80:3000"