# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: |
        cd server/
        npm ci
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: server/
          file: server/Dockerfile
          push: true
          tags: vbonzon/t99-backend:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}




        #uses: docker/build-push-action@v5
        #with:
        #  context: server/
        #  file: server/Dockerfile
        #  push: ${{github.ref == 'refs/heads/main'}}
        #  tags: ghcr.io/vbonzon/t99-backend:latest


