# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: workflow

on:
  push:
    branches: [ "main" , "socketIO"]
  pull_request:
    branches: [ "main" ]
jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: server/backend/package-lock.json
    - run: |
        cd server/backend/
        npm ci
        npm test

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: server/backend
          push: true
          tags: xgcdkr/trivia99-backend:latest


